#############################################################################
# Makefile for building: KylinSystemMonitor
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  KylinSystemMonitor.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile KylinSystemMonitor.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -isystem /usr/include/c++/11 -isystem /usr/include/x86_64-linux-gnu/c++/11 -O2 -pthread -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Icontroller -Imodel -Iview -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = KylinSystemMonitor1.0.0
DISTDIR = /home/china/桌面/KylinSystemMonitor/.tmp/KylinSystemMonitor1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -pthread -lssl -lcrypto /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = controller/processcontroller.cpp \
		controller/systemcontroller.cpp \
		controller/filesystemcontroller.cpp \
		controller/exportcontroller.cpp \
		model/processmodel.cpp \
		model/systemmodel.cpp \
		model/sensorsreader.cpp \
		model/sensormodel.cpp \
		service/asyncmonitor.cpp \
		service/cryptohelper.cpp \
		view/systemoverviewwidget.cpp \
		view/resourcemonitorwidget.cpp \
		view/processmanagerwidget.cpp \
		view/filesystemmonitor.cpp \
		view/dataexportwidget.cpp \
		view/processreportdialog.cpp \
		main.cpp \
		mainwindow.cpp moc_processcontroller.cpp \
		moc_systemcontroller.cpp \
		moc_filesystemcontroller.cpp \
		moc_exportcontroller.cpp \
		moc_processmodel.cpp \
		moc_systemmodel.cpp \
		moc_sensorsreader.cpp \
		moc_sensormodel.cpp \
		moc_asyncmonitor.cpp \
		moc_cryptohelper.cpp \
		moc_systemoverviewwidget.cpp \
		moc_resourcemonitorwidget.cpp \
		moc_processmanagerwidget.cpp \
		moc_filesystemmonitor.cpp \
		moc_dataexportwidget.cpp \
		moc_processreportdialog.cpp \
		moc_mainwindow.cpp
OBJECTS       = processcontroller.o \
		systemcontroller.o \
		filesystemcontroller.o \
		exportcontroller.o \
		processmodel.o \
		systemmodel.o \
		sensorsreader.o \
		sensormodel.o \
		asyncmonitor.o \
		cryptohelper.o \
		systemoverviewwidget.o \
		resourcemonitorwidget.o \
		processmanagerwidget.o \
		filesystemmonitor.o \
		dataexportwidget.o \
		processreportdialog.o \
		main.o \
		mainwindow.o \
		moc_processcontroller.o \
		moc_systemcontroller.o \
		moc_filesystemcontroller.o \
		moc_exportcontroller.o \
		moc_processmodel.o \
		moc_systemmodel.o \
		moc_sensorsreader.o \
		moc_sensormodel.o \
		moc_asyncmonitor.o \
		moc_cryptohelper.o \
		moc_systemoverviewwidget.o \
		moc_resourcemonitorwidget.o \
		moc_processmanagerwidget.o \
		moc_filesystemmonitor.o \
		moc_dataexportwidget.o \
		moc_processreportdialog.o \
		moc_mainwindow.o
DIST          = cpu_profile.sh \
		memcheck.sh \
		performance_test.sh \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		KylinSystemMonitor.pro controller/processcontroller.h \
		controller/systemcontroller.h \
		controller/filesystemcontroller.h \
		controller/exportcontroller.h \
		model/processmodel.h \
		model/systemmodel.h \
		model/sensorsreader.h \
		model/sensormodel.h \
		service/asyncmonitor.h \
		service/cryptohelper.h \
		view/systemoverviewwidget.h \
		view/resourcemonitorwidget.h \
		view/processmanagerwidget.h \
		view/filesystemmonitor.h \
		view/dataexportwidget.h \
		view/processreportdialog.h \
		mainwindow.h controller/processcontroller.cpp \
		controller/systemcontroller.cpp \
		controller/filesystemcontroller.cpp \
		controller/exportcontroller.cpp \
		model/processmodel.cpp \
		model/systemmodel.cpp \
		model/sensorsreader.cpp \
		model/sensormodel.cpp \
		service/asyncmonitor.cpp \
		service/cryptohelper.cpp \
		view/systemoverviewwidget.cpp \
		view/resourcemonitorwidget.cpp \
		view/processmanagerwidget.cpp \
		view/filesystemmonitor.cpp \
		view/dataexportwidget.cpp \
		view/processreportdialog.cpp \
		main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = KylinSystemMonitor
DESTDIR       = 
TARGET        = KylinSystemMonitor


first: all
####### Build rules

KylinSystemMonitor:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: KylinSystemMonitor.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		KylinSystemMonitor.pro
	$(QMAKE) -o Makefile KylinSystemMonitor.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
KylinSystemMonitor.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile KylinSystemMonitor.pro

qmake_all: FORCE


all: Makefile KylinSystemMonitor

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents controller/processcontroller.h controller/systemcontroller.h controller/filesystemcontroller.h controller/exportcontroller.h model/processmodel.h model/systemmodel.h model/sensorsreader.h model/sensormodel.h service/asyncmonitor.h service/cryptohelper.h view/systemoverviewwidget.h view/resourcemonitorwidget.h view/processmanagerwidget.h view/filesystemmonitor.h view/dataexportwidget.h view/processreportdialog.h mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents controller/processcontroller.cpp controller/systemcontroller.cpp controller/filesystemcontroller.cpp controller/exportcontroller.cpp model/processmodel.cpp model/systemmodel.cpp model/sensorsreader.cpp model/sensormodel.cpp service/asyncmonitor.cpp service/cryptohelper.cpp view/systemoverviewwidget.cpp view/resourcemonitorwidget.cpp view/processmanagerwidget.cpp view/filesystemmonitor.cpp view/dataexportwidget.cpp view/processreportdialog.cpp main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents /home/china/桌面/KylinSystemMonitor/KylinSystemMonitor_zh_CN.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -isystem /usr/include/c++/11 -isystem /usr/include/x86_64-linux-gnu/c++/11 -O2 -pthread -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_processcontroller.cpp moc_systemcontroller.cpp moc_filesystemcontroller.cpp moc_exportcontroller.cpp moc_processmodel.cpp moc_systemmodel.cpp moc_sensorsreader.cpp moc_sensormodel.cpp moc_asyncmonitor.cpp moc_cryptohelper.cpp moc_systemoverviewwidget.cpp moc_resourcemonitorwidget.cpp moc_processmanagerwidget.cpp moc_filesystemmonitor.cpp moc_dataexportwidget.cpp moc_processreportdialog.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_processcontroller.cpp moc_systemcontroller.cpp moc_filesystemcontroller.cpp moc_exportcontroller.cpp moc_processmodel.cpp moc_systemmodel.cpp moc_sensorsreader.cpp moc_sensormodel.cpp moc_asyncmonitor.cpp moc_cryptohelper.cpp moc_systemoverviewwidget.cpp moc_resourcemonitorwidget.cpp moc_processmanagerwidget.cpp moc_filesystemmonitor.cpp moc_dataexportwidget.cpp moc_processreportdialog.cpp moc_mainwindow.cpp
moc_processcontroller.cpp: controller/processcontroller.h \
		model/processmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controller/processcontroller.h -o moc_processcontroller.cpp

moc_systemcontroller.cpp: controller/systemcontroller.h \
		model/systemmodel.h \
		model/sensormodel.h \
		model/processmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controller/systemcontroller.h -o moc_systemcontroller.cpp

moc_filesystemcontroller.cpp: controller/filesystemcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controller/filesystemcontroller.h -o moc_filesystemcontroller.cpp

moc_exportcontroller.cpp: controller/exportcontroller.h \
		model/systemmodel.h \
		model/processmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controller/exportcontroller.h -o moc_exportcontroller.cpp

moc_processmodel.cpp: model/processmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include model/processmodel.h -o moc_processmodel.cpp

moc_systemmodel.cpp: model/systemmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include model/systemmodel.h -o moc_systemmodel.cpp

moc_sensorsreader.cpp: model/sensorsreader.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include model/sensorsreader.h -o moc_sensorsreader.cpp

moc_sensormodel.cpp: model/sensormodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include model/sensormodel.h -o moc_sensormodel.cpp

moc_asyncmonitor.cpp: service/asyncmonitor.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include service/asyncmonitor.h -o moc_asyncmonitor.cpp

moc_cryptohelper.cpp: service/cryptohelper.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include service/cryptohelper.h -o moc_cryptohelper.cpp

moc_systemoverviewwidget.cpp: view/systemoverviewwidget.h \
		model/systemmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/systemoverviewwidget.h -o moc_systemoverviewwidget.cpp

moc_resourcemonitorwidget.cpp: view/resourcemonitorwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/resourcemonitorwidget.h -o moc_resourcemonitorwidget.cpp

moc_processmanagerwidget.cpp: view/processmanagerwidget.h \
		model/processmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/processmanagerwidget.h -o moc_processmanagerwidget.cpp

moc_filesystemmonitor.cpp: view/filesystemmonitor.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/filesystemmonitor.h -o moc_filesystemmonitor.cpp

moc_dataexportwidget.cpp: view/dataexportwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/dataexportwidget.h -o moc_dataexportwidget.cpp

moc_processreportdialog.cpp: view/processreportdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include view/processreportdialog.h -o moc_processreportdialog.cpp

moc_mainwindow.cpp: mainwindow.h \
		controller/systemcontroller.h \
		model/systemmodel.h \
		model/sensormodel.h \
		model/processmodel.h \
		controller/exportcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/china/桌面/KylinSystemMonitor/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor -I/home/china/桌面/KylinSystemMonitor/controller -I/home/china/桌面/KylinSystemMonitor/model -I/home/china/桌面/KylinSystemMonitor/view -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

processcontroller.o: controller/processcontroller.cpp controller/processcontroller.h \
		model/processmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processcontroller.o controller/processcontroller.cpp

systemcontroller.o: controller/systemcontroller.cpp controller/systemcontroller.h \
		model/systemmodel.h \
		model/sensormodel.h \
		model/processmodel.h \
		service/asyncmonitor.h \
		controller/processcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemcontroller.o controller/systemcontroller.cpp

filesystemcontroller.o: controller/filesystemcontroller.cpp controller/filesystemcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filesystemcontroller.o controller/filesystemcontroller.cpp

exportcontroller.o: controller/exportcontroller.cpp controller/exportcontroller.h \
		model/systemmodel.h \
		model/processmodel.h \
		service/cryptohelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportcontroller.o controller/exportcontroller.cpp

processmodel.o: model/processmodel.cpp model/processmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processmodel.o model/processmodel.cpp

systemmodel.o: model/systemmodel.cpp model/systemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemmodel.o model/systemmodel.cpp

sensorsreader.o: model/sensorsreader.cpp model/sensorsreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensorsreader.o model/sensorsreader.cpp

sensormodel.o: model/sensormodel.cpp model/sensormodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensormodel.o model/sensormodel.cpp

asyncmonitor.o: service/asyncmonitor.cpp service/asyncmonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o asyncmonitor.o service/asyncmonitor.cpp

cryptohelper.o: service/cryptohelper.cpp service/cryptohelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cryptohelper.o service/cryptohelper.cpp

systemoverviewwidget.o: view/systemoverviewwidget.cpp view/systemoverviewwidget.h \
		model/systemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemoverviewwidget.o view/systemoverviewwidget.cpp

resourcemonitorwidget.o: view/resourcemonitorwidget.cpp view/resourcemonitorwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resourcemonitorwidget.o view/resourcemonitorwidget.cpp

processmanagerwidget.o: view/processmanagerwidget.cpp view/processmanagerwidget.h \
		model/processmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processmanagerwidget.o view/processmanagerwidget.cpp

filesystemmonitor.o: view/filesystemmonitor.cpp view/filesystemmonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filesystemmonitor.o view/filesystemmonitor.cpp

dataexportwidget.o: view/dataexportwidget.cpp view/dataexportwidget.h \
		controller/exportcontroller.h \
		model/systemmodel.h \
		model/processmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataexportwidget.o view/dataexportwidget.cpp

processreportdialog.o: view/processreportdialog.cpp view/processreportdialog.h \
		model/processmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processreportdialog.o view/processreportdialog.cpp

main.o: main.cpp mainwindow.h \
		controller/systemcontroller.h \
		model/systemmodel.h \
		model/sensormodel.h \
		model/processmodel.h \
		controller/exportcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		controller/systemcontroller.h \
		model/systemmodel.h \
		model/sensormodel.h \
		model/processmodel.h \
		controller/exportcontroller.h \
		view/systemoverviewwidget.h \
		view/processmanagerwidget.h \
		view/resourcemonitorwidget.h \
		view/filesystemmonitor.h \
		view/dataexportwidget.h \
		controller/processcontroller.h \
		controller/filesystemcontroller.h \
		view/processreportdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_processcontroller.o: moc_processcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_processcontroller.o moc_processcontroller.cpp

moc_systemcontroller.o: moc_systemcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systemcontroller.o moc_systemcontroller.cpp

moc_filesystemcontroller.o: moc_filesystemcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filesystemcontroller.o moc_filesystemcontroller.cpp

moc_exportcontroller.o: moc_exportcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportcontroller.o moc_exportcontroller.cpp

moc_processmodel.o: moc_processmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_processmodel.o moc_processmodel.cpp

moc_systemmodel.o: moc_systemmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systemmodel.o moc_systemmodel.cpp

moc_sensorsreader.o: moc_sensorsreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sensorsreader.o moc_sensorsreader.cpp

moc_sensormodel.o: moc_sensormodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sensormodel.o moc_sensormodel.cpp

moc_asyncmonitor.o: moc_asyncmonitor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_asyncmonitor.o moc_asyncmonitor.cpp

moc_cryptohelper.o: moc_cryptohelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cryptohelper.o moc_cryptohelper.cpp

moc_systemoverviewwidget.o: moc_systemoverviewwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systemoverviewwidget.o moc_systemoverviewwidget.cpp

moc_resourcemonitorwidget.o: moc_resourcemonitorwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resourcemonitorwidget.o moc_resourcemonitorwidget.cpp

moc_processmanagerwidget.o: moc_processmanagerwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_processmanagerwidget.o moc_processmanagerwidget.cpp

moc_filesystemmonitor.o: moc_filesystemmonitor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filesystemmonitor.o moc_filesystemmonitor.cpp

moc_dataexportwidget.o: moc_dataexportwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataexportwidget.o moc_dataexportwidget.cpp

moc_processreportdialog.o: moc_processreportdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_processreportdialog.o moc_processreportdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/KylinSystemMonitor/bin || mkdir -p $(INSTALL_ROOT)/opt/KylinSystemMonitor/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/KylinSystemMonitor/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/KylinSystemMonitor/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/KylinSystemMonitor/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/KylinSystemMonitor/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

